name: Build INAV Configurator (GATED)

on:
  workflow_dispatch:
  push:
    paths:
      - 'external-configurator_mod/**'
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        shell: bash
        run: |
          COMMIT_ID=${{ github.sha }}
          BUILD_SUFFIX=ci-$(date "+%Y%m%d")-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version external-configurator_mod/package.json | sed "s/.*"\([0-9][0-9]*.[0-9]*.[0-9]*\)".*//g")
          echo "BUILD_NAMEx64=INAV-Configurator-GATED_Windows64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: engineerd/configurator@v0.0.10
        with:
          name: "Wix Toolset 3.1.4"
          url: "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip"
          pathInArchive: "/"

      - name: Install deps
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          command: yarn install --foreground-scripts
          timeout_minutes: 10
          on_retry_command: rm -rfv external-configurator_mod/node_modules
        env:
          working-directory: external-configurator_mod

      - name: Build Windows x64
        working-directory: external-configurator_mod
        run: yarn run make -- --arch="x64"

      - name: Upload Windows x64 ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAMEx64 }}_ZIP
          path: external-configurator_mod/out/make/zip/win32/x64/*.zip

      - name: Upload Windows x64 MSI
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAMEx64 }}_MSI
          path: external-configurator_mod/out/make/wix/x64/*.msi
